version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
